[package]
name        = "cw-coins"
description = "Helper functions for managing multiple coins"
version     = { workspace = true }
authors     = { workspace = true }
edition     = { workspace = true }
homepage    = { workspace = true }
repository  = { workspace = true }
license     = { workspace = true }
keywords    = { workspace = true }

[dependencies]
cosmwasm-std = { workspace = true }
schemars     = { workspace = true }
serde        = { workspace = true, features = ["derive"] }

[dev-dependencies]
serde_json = "1.0"
