[workspace]
members = ["packages/*"]

[workspace.package]
version    = "0.6.0"
authors    = ["larry <gm@larry.engineer>"]
edition    = "2021"
homepage   = "https://larry.engineer"
repository = "https://github.com/stake-enjoyers/cw-plus-plus"
license    = "AGPL-3.0-or-later"
keywords   = ["cosmos", "cosmwasm"]

[workspace.dependencies]
cosmwasm-std    = "1.1"
cw-storage-plus = "0.16"
schemars        = "0.8"
serde           = { version = "1.0", default-features = false }

[profile.release]
debug            = false
debug-assertions = false
lto              = true
opt-level        = 3
overflow-checks  = true
rpath            = false
