[workspace]
members = ["packages/*"]

[workspace.package]
authors    = ["larry <gm@larry.engineer>"]
edition    = "2021"
homepage   = "https://larry.engineer"
repository = "https://github.com/steak-enjoyers/cw-plus-plus"
license    = "AGPL-3.0-or-later"
keywords   = ["cosmos", "cosmwasm"]

[workspace.dependencies]
cosmwasm-std    = "1.1"
cw-storage-plus = "1.0"
